# Generated by Django 5.0 on 2024-01-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_chartsmod_multitracksmod_produccionesmod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionesmod',
            name='politica',
            field=models.BooleanField(default=False),
        ),
    ]
